# Generated by Django 4.0.1 on 2022-01-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
