# Generated by Django 4.0.1 on 2022-01-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Ser_vice',
        ),
    ]
